"""
Configuration for the Legal RAG Chatbot.
Loads environment variables and defines all paths, model names, and settings.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# --- Paths ---
BASE_DIR = Path(__file__).resolve().parent.parent
DATA_SOURCES_DIR = BASE_DIR / "Data Sources"
CHROMA_DB_DIR = str(BASE_DIR / "chroma_db")

# Data source paths
CONSTITUTION_DIR = DATA_SOURCES_DIR / "Constitution of India "
INDIA_CODE_DIR = DATA_SOURCES_DIR / "India Code" / "central-acts"
SC_JUDGMENTS_DIR = DATA_SOURCES_DIR / "Supreme Court Judgement Dataset"
RBI_CIRCULARS_DIR = DATA_SOURCES_DIR / "RBI Circulars"
SEBI_INSTRUCTIONS_DIR = DATA_SOURCES_DIR / "SEBI Instructions"

# --- API Keys ---
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")

# --- Model Configuration ---
EMBEDDING_MODEL_NAME = "BAAI/bge-m3"
RERANKER_MODEL_NAME = "BAAI/bge-reranker-v2-m3"
LLM_MODEL_NAME = "llama3.1"

# --- Chunking Configuration ---
MAX_CHUNK_SIZE = 6000          # characters (safe within BGE-M3's 8K token window)
MIN_CHUNK_SIZE = 100           # characters (merge if smaller)
CHUNK_OVERLAP = 200            # characters overlap for sub-splitting

# --- Retriever Configuration ---
MULTI_QUERY_COUNT = 6          # Number of queries generated by MultiQueryRetriever
RETRIEVER_TOP_K = 20           # Initial retrieval candidates per query
RERANKER_TOP_N = 6             # Final results after reranking

# --- Memory Configuration ---
MEMORY_WINDOW_SIZE = 10        # Number of conversation exchanges to keep

# --- ChromaDB Configuration ---
CHROMA_COLLECTION_NAME = "legal_documents"

# --- Flask Configuration ---
FLASK_HOST = "0.0.0.0"
FLASK_PORT = 5000
FLASK_DEBUG = True
